title: Python Programming Lab
tagline: A brand new course on Learning Lab
description: >-
  Python Programming Lab is a platform to enhance the skills in python
  programming languages
template:
  repo: python-programming-lab-template
  name: python-programming-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
